# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f6a8a2b30c0e8edc3558d89c589312e8cbdb2f4c0546a6a967bc6b47ec75a44c65c0da112d11aa027a7505c467023defcfaa0ba3e47bc630d38b2b64da70233

test:
  secret_key_base: 92790f4460b3de17dbd9fe94029bc5d7be5942a92be4b328139975ba80f517e69aea4dc286f4dd08bd9c2a033a4812851228db6a8a31a842a03013f0823a952a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
